//! Regression gates for the BF16x product build (FMA contraction, -fmad=true):
//! - identical input, options and seed give byte-identical WAVs on every run (reproducibility);
//! - disabling the batch gap masking (fault hook KOKORO_BATCH_NEGCTL_NOMASK) changes outputs, so
//!   cross-item leakage would be visible (negative control against the same binary);
//! - the per-line hash comparison catches changed, missing and extra lines (checker controls);
//! - the public pinned cases reproduce the FMA reference table tests/pinned/bf16x_fma_golden.json byte
//!   for byte. That table was generated by bench/make_bf16x_golden.py --fma-pin from the build of
//!   commit b4777ce (binary sha256 recorded in the table). It is a reproducibility pin for this
//!   build configuration, not a quality acceptance; re-pinning after an intended numerical change
//!   must be a visible, separately reviewed commit.
//! The earlier strict-rounding artifact is compared separately (tests/strict_reference_diff.rs,
//! diagnostic only).
//! Renders use the reference eSpeak NG copy the tables were made with (tests/support/paths.rs). The
//! tables predate the no-dropped-words rule: the reference silently dropped "-12" on line 7 of
//! bench/frontend_edge_cases.txt (its oracle record gives the token no phonemes). The binary now
//! refuses that line (EXPECTED_REFUSED). In the batched edge cases this also changes how the other
//! lines are batched, so those cases are reported rather than compared (BATCH_RECOMPOSED); every
//! other pinned case, including the one-item-per-batch edge case, must still match line for line.

#[path = "support/golden.rs"]
mod golden;
use golden::paths;
use std::collections::BTreeMap;

fn edge_case() -> (std::path::PathBuf, Vec<String>) {
    let input = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("bench/frontend_edge_cases.txt");
    (input, vec!["--format".into(), "float32".into()])
}

fn as_table(h: &BTreeMap<usize, String>) -> serde_json::Map<String, serde_json::Value> {
    h.iter().map(|(k, v)| (k.to_string(), serde_json::json!(v))).collect()
}

#[test]
fn reproducible_across_runs() {
    let (input, args) = edge_case();
    for voice in ["af_heart", "am_adam"] {
        let a = golden::render(&input, voice, &args, &paths::scratch(&["regression", voice, "run1"]));
        let b = golden::render(&input, voice, &args, &paths::scratch(&["regression", voice, "run2"]));
        assert_eq!(a.len(), 65, "{voice}: every line rendered");
        let d = golden::diff(&b, &as_table(&a));
        assert!(d.is_empty(), "{voice}: two runs differ: {d:?}");
        println!("{voice}: {} lines byte-identical across two runs", a.len());
    }
}

#[test]
fn detects_cross_item_leakage() {
    let (input, args) = edge_case();
    let good = golden::render(&input, "af_heart", &args, &paths::scratch(&["regression", "negctl", "masked"]));
    let bad = golden::render_env(&input, "af_heart", &args, &paths::scratch(&["regression", "negctl", "unmasked"]), &[("KOKORO_BATCH_NEGCTL_NOMASK", "1")]);
    let d = golden::diff(&bad, &as_table(&good));
    println!("gap masking disabled: {} of {} lines differ", d.len(), good.len());
    assert!(!d.is_empty(), "cross-item leakage was not detected");
}

#[test]
fn checker_negative_controls() {
    let mut want = serde_json::Map::new();
    want.insert("1".into(), serde_json::json!("a".repeat(64)));
    want.insert("2".into(), serde_json::json!("b".repeat(64)));
    let ok: BTreeMap<usize, String> = [(1, "a".repeat(64)), (2, "b".repeat(64))].into();
    assert!(golden::diff(&ok, &want).is_empty());
    let changed: BTreeMap<usize, String> = [(1, "a".repeat(64)), (2, "c".repeat(64))].into();
    assert_eq!(golden::diff(&changed, &want).len(), 1);
    let missing: BTreeMap<usize, String> = [(1, "a".repeat(64))].into();
    assert_eq!(golden::diff(&missing, &want).len(), 1);
    let extra: BTreeMap<usize, String> = [(1, "a".repeat(64)), (2, "b".repeat(64)), (3, "d".repeat(64))].into();
    assert_eq!(golden::diff(&extra, &want).len(), 1);
}

/// Pinned lines the binary now refuses under the no-dropped-words rule: (case input, lines).
const EXPECTED_REFUSED: &[(&str, &[usize])] = &[("bench/frontend_edge_cases.txt", &[7])];

/// Pinned cases whose batches contained a now-refused line. Without it the other lines are batched
/// differently, and the BF16 predictor depends on the batch composition (docs/design/BATCHING.md),
/// so their other lines are reported, not compared. edge_am_items1 (one item per batch) still
/// compares every other line: the per-item outputs are unchanged.
const BATCH_RECOMPOSED: &[&str] = &["edge_af", "edge_am", "edge_af_speed0.8"];

fn check_table(table: &serde_json::Value, input_override: Option<&std::path::Path>, scratch: &std::path::Path) {
    let rows = golden::run_table(table, input_override, scratch);
    let mut failures = vec![];
    for (case, n, d) in &rows {
        let input = table["cases"][case]["input"].as_str().unwrap_or("");
        let expected: Vec<usize> = EXPECTED_REFUSED.iter().filter(|(i, _)| *i == input).flat_map(|(_, l)| l.iter().copied()).collect();
        let (refused, d): (Vec<String>, Vec<String>) = d.iter().cloned().partition(|x| x.contains(golden::UNRESOLVED));
        let refused_lines: Vec<usize> = refused.iter().map(|x| x.trim_start_matches("line ").split(':').next().unwrap().parse().unwrap()).collect();
        let recomposed = BATCH_RECOMPOSED.contains(&case.as_str());
        println!(
            "{case}: {n} lines, {} refused (unresolved word: {refused_lines:?}), {} other differences from the FMA pin{}",
            refused.len(),
            d.len(),
            if recomposed { " (batch recomposed: reported, not compared)" } else { "" }
        );
        if refused_lines != expected {
            failures.push(format!("{case}: refused lines {refused_lines:?} != expected {expected:?}"));
        }
        if recomposed {
            if d.iter().any(|x| x.contains("missing") || x.contains("extra")) {
                failures.push(format!("{case}: line coverage differs: {d:?}"));
            }
            continue;
        }
        if !d.is_empty() {
            failures.push(format!("{case}: {} lines differ; first: {:?}", d.len(), &d[..d.len().min(3)]));
        }
    }
    assert!(failures.is_empty(), "outputs differ from the FMA reference pin:\n{}", failures.join("\n"));
}

#[test]
fn public_cases_match_fma_pin() {
    let table: serde_json::Value = serde_json::from_str(include_str!("pinned/bf16x_fma_golden.json")).unwrap();
    assert_eq!(table["build"], "nvcc -arch=compute_89 -fmad=true -O3 (FMA contraction)");
    check_table(&table, None, &paths::scratch(&["regression", "fma_pin_public"]));
}

/// Optional private long-form text (KOKORO_PRIVATE_CHAPTER; pin under the data root, never in Git).
#[test]
#[ignore = "private text (local only; KOKORO_PRIVATE_CHAPTER)"]
fn private_text_matches_fma_pin() {
    let t = paths::data().join("evidence/private/fma-golden/private_fma_golden.json");
    let table: serde_json::Value = serde_json::from_str(&std::fs::read_to_string(t).unwrap()).unwrap();
    check_table(&table, Some(&paths::private_chapter()), &paths::scratch(&["regression", "fma_pin_private"]));
}
