//! Regression gates for the BF16x product build (FMA contraction, -fmad=true):
//! - identical input, options and seed give byte-identical WAVs on every run (reproducibility);
//! - disabling the batch gap masking (fault hook KOKORO_BATCH_NEGCTL_NOMASK) changes outputs, so
//!   cross-item leakage would be visible (negative control against the same binary);
//! - the per-line hash comparison catches changed, missing and extra lines (checker controls);
//! - the public pinned cases reproduce the FMA reference table tests/pinned/bf16x_fma_golden.json byte
//!   for byte. That table was generated by bench/make_bf16x_golden.py --fma-pin from the build of
//!   commit b4777ce (binary sha256 recorded in the table). It is a reproducibility pin for this
//!   build configuration, not a quality acceptance; re-pinning after an intended numerical change
//!   must be a visible, separately reviewed commit.
//! The earlier strict-rounding artifact is compared separately (tests/strict_reference_diff.rs,
//! diagnostic only).

#[path = "support/golden.rs"]
mod golden;
use golden::paths;
use std::collections::BTreeMap;

fn edge_case() -> (std::path::PathBuf, Vec<String>) {
    let input = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("bench/frontend_edge_cases.txt");
    (input, vec!["--format".into(), "float32".into()])
}

fn as_table(h: &BTreeMap<usize, String>) -> serde_json::Map<String, serde_json::Value> {
    h.iter().map(|(k, v)| (k.to_string(), serde_json::json!(v))).collect()
}

#[test]
fn reproducible_across_runs() {
    let (input, args) = edge_case();
    for voice in ["af_heart", "am_adam"] {
        let a = golden::render(&input, voice, &args, &paths::scratch(&["regression", voice, "run1"]));
        let b = golden::render(&input, voice, &args, &paths::scratch(&["regression", voice, "run2"]));
        assert_eq!(a.len(), 65, "{voice}: every line rendered");
        let d = golden::diff(&b, &as_table(&a));
        assert!(d.is_empty(), "{voice}: two runs differ: {d:?}");
        println!("{voice}: {} lines byte-identical across two runs", a.len());
    }
}

#[test]
fn detects_cross_item_leakage() {
    let (input, args) = edge_case();
    let good = golden::render(&input, "af_heart", &args, &paths::scratch(&["regression", "negctl", "masked"]));
    let bad = golden::render_env(&input, "af_heart", &args, &paths::scratch(&["regression", "negctl", "unmasked"]), &[("KOKORO_BATCH_NEGCTL_NOMASK", "1")]);
    let d = golden::diff(&bad, &as_table(&good));
    println!("gap masking disabled: {} of {} lines differ", d.len(), good.len());
    assert!(!d.is_empty(), "cross-item leakage was not detected");
}

#[test]
fn checker_negative_controls() {
    let mut want = serde_json::Map::new();
    want.insert("1".into(), serde_json::json!("a".repeat(64)));
    want.insert("2".into(), serde_json::json!("b".repeat(64)));
    let ok: BTreeMap<usize, String> = [(1, "a".repeat(64)), (2, "b".repeat(64))].into();
    assert!(golden::diff(&ok, &want).is_empty());
    let changed: BTreeMap<usize, String> = [(1, "a".repeat(64)), (2, "c".repeat(64))].into();
    assert_eq!(golden::diff(&changed, &want).len(), 1);
    let missing: BTreeMap<usize, String> = [(1, "a".repeat(64))].into();
    assert_eq!(golden::diff(&missing, &want).len(), 1);
    let extra: BTreeMap<usize, String> = [(1, "a".repeat(64)), (2, "b".repeat(64)), (3, "d".repeat(64))].into();
    assert_eq!(golden::diff(&extra, &want).len(), 1);
}

fn check_table(table: &serde_json::Value, input_override: Option<&std::path::Path>, scratch: &std::path::Path) {
    let rows = golden::run_table(table, input_override, scratch);
    let mut failures = vec![];
    for (case, n, d) in &rows {
        println!("{case}: {n} lines, {} differences from the FMA pin", d.len());
        if !d.is_empty() {
            failures.push(format!("{case}: {} lines differ; first: {:?}", d.len(), &d[..d.len().min(3)]));
        }
    }
    assert!(failures.is_empty(), "outputs differ from the FMA reference pin:\n{}", failures.join("\n"));
}

#[test]
fn public_cases_match_fma_pin() {
    let table: serde_json::Value = serde_json::from_str(include_str!("pinned/bf16x_fma_golden.json")).unwrap();
    assert_eq!(table["build"], "nvcc -arch=compute_89 -fmad=true -O3 (FMA contraction)");
    check_table(&table, None, &paths::scratch(&["regression", "fma_pin_public"]));
}

/// Optional private long-form text (KOKORO_PRIVATE_CHAPTER; pin under the data root, never in Git).
#[test]
#[ignore = "private text (local only; KOKORO_PRIVATE_CHAPTER)"]
fn private_text_matches_fma_pin() {
    let t = paths::data().join("evidence/private/fma-golden/private_fma_golden.json");
    let table: serde_json::Value = serde_json::from_str(&std::fs::read_to_string(t).unwrap()).unwrap();
    check_table(&table, Some(&paths::private_chapter()), &paths::scratch(&["regression", "fma_pin_private"]));
}
