"""Generate src/frontend/pyunicode.rs (exact Python 3.12.3 / Unicode 15.0.0 str semantics tables) from
the pystr_oracle.py JSON. Unicode character data only; regenerate if the reference Python changes.
Usage: python oracle/gen_pyunicode.py <pystr_unicode.json> src/frontend/pyunicode.rs
"""
import json
import pathlib
import sys


def rs_str(s):
    esc = []
    for c in s:
        if c.isascii() and c.isprintable() and c not in "\"\\":
            esc.append(c)
        else:
            esc.append("\\u{%x}" % ord(c))
    return '"' + "".join(esc) + '"'


def main():
    t = json.loads(pathlib.Path(sys.argv[1]).read_text())
    out = [f"//! GENERATED by oracle/gen_pyunicode.py from the pinned reference interpreter (Python {t['python']},",
           f"//! Unicode {t['unicodedata']}); do not edit. Exact str semantics tables for src/frontend/pystr.rs.", "",
           f"pub const PYTHON: &str = \"{t['python']}\";", f"pub const UNICODE: &str = \"{t['unicodedata']}\";", ""]
    for k in ("isalpha", "isspace", "isupper", "sigma_cased", "sigma_ignorable"):
        out.append(f"pub static {k.upper()}: &[(u32, u32)] = &[" + ", ".join(f"({a}, {b})" for a, b in t[k]) + "];")
    # digits as runs (start, end, value_at_start) with value incrementing by one
    ds = sorted((int(k), v) for k, v in t["isdigit"].items())
    runs = []
    for cp, v in ds:
        if runs and runs[-1][1] == cp - 1 and runs[-1][2] + (cp - runs[-1][0]) == v:
            runs[-1][1] = cp
        else:
            runs.append([cp, cp, v])
    out.append("pub static DIGITS: &[(u32, u32, u32)] = &[" + ", ".join(f"({a}, {b}, {v})" for a, b, v in runs) + "];")
    for k in ("lower", "upper", "title"):
        items = sorted((int(a), b) for a, b in t[k].items())
        out.append(f"pub static {k.upper()}: &[(u32, &str)] = &[" + ", ".join(f"({a}, {rs_str(b)})" for a, b in items) + "];")
    pathlib.Path(sys.argv[2]).write_text("\n".join(out) + "\n")
    print("wrote", sys.argv[2], "digit runs", len(runs))


if __name__ == "__main__":
    main()
